#!/usr/bin/bash
# Maintainer  : Vilmar Catafesta <vcatafesta@gmail.com>

pkgname=chili-tradutor-go
pkgdesc="Wrapper universal de tradução automática com cache inteligente"
pkgver=$(date +%Y%m%d)
pkgrel=$(date +%H%M)
arch=('any')
license=('MIT')
url="https://github.com/chililinux/$pkgname"
provides=("$pkgname")
source=("git+${url}.git")
md5sums=('SKIP')
depends=("bash>=0" gettext translate-shell)

package() {
	# Verify default folder
	if [ -d "${srcdir}/${pkgname}/${pkgname}" ]; then
		InternalDir="${srcdir}/${pkgname}/${pkgname}"
	elif [ -d "${srcdir}/${pkgname}" ]; then
		InternalDir="${srcdir}/${pkgname}"
	else
		#local
		InternalDir="${WORKDIR}"
	fi

	cd "${InternalDir}"
	# Copiar a estrutura de /etc, /usr e /opt para /
	local dirs=("boot" "etc" "opt" "usr" "var")
	for dir in "${dirs[@]}"; do
		if [ -d "${InternalDir}/${dir}" ]; then
			cp -a "${InternalDir}/${dir}" "${pkgdir}/"
		fi
	done

	# Install license file if present
	if [ -f "LICENSE" ]; then
		install -Dm644 LICENSE "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
	fi

	# Install documentation if present
	if [ -f "README.md" ]; then
		install -Dm644 README.md "${pkgdir}/usr/share/doc/${pkgname}/README.md"
	fi
}

pre_install() {
	log "Iniciando instalação"
}

post_install() {
	log "Finalizando instalação"
}

pre_upgrade() {
	log "Iniciando upgrade"
}

post_upgrade() {
	log "Finalizando upgrade"
}
